add_test( BoundaryTest.AnalyticSlipFree /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=BoundaryTest.AnalyticSlipFree]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.AnalyticSlipFree PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BoundaryTest.AnalyticSlipStick /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=BoundaryTest.AnalyticSlipStick]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.AnalyticSlipStick PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BoundaryTest.MIBF /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=BoundaryTest.MIBF]==] --gtest_also_run_disabled_tests)
set_tests_properties( BoundaryTest.MIBF PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CoulombFrictionTest.PlateSlipFree /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=CoulombFrictionTest.PlateSlipFree]==] --gtest_also_run_disabled_tests)
set_tests_properties( CoulombFrictionTest.PlateSlipFree PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CoulombFrictionTest.PlateSlipStick /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=CoulombFrictionTest.PlateSlipStick]==] --gtest_also_run_disabled_tests)
set_tests_properties( CoulombFrictionTest.PlateSlipStick PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CoulombFrictionTest.GeneralSlipFree /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=CoulombFrictionTest.GeneralSlipFree]==] --gtest_also_run_disabled_tests)
set_tests_properties( CoulombFrictionTest.GeneralSlipFree PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CoulombFrictionTest.GeneralSlipStick /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=CoulombFrictionTest.GeneralSlipStick]==] --gtest_also_run_disabled_tests)
set_tests_properties( CoulombFrictionTest.GeneralSlipStick PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ElasticityTest.BulkModulus /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=ElasticityTest.BulkModulus]==] --gtest_also_run_disabled_tests)
set_tests_properties( ElasticityTest.BulkModulus PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( EnergyTest.Rotation /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=EnergyTest.Rotation]==] --gtest_also_run_disabled_tests)
set_tests_properties( EnergyTest.Rotation PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CollapseTest.DruckerPragerOne /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=CollapseTest.DruckerPragerOne]==] --gtest_also_run_disabled_tests)
set_tests_properties( CollapseTest.DruckerPragerOne PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CollapseTest.DruckerPragerTwo /common/home/twm70/Repos/matter/tests/tests [==[--gtest_filter=CollapseTest.DruckerPragerTwo]==] --gtest_also_run_disabled_tests)
set_tests_properties( CollapseTest.DruckerPragerTwo PROPERTIES WORKING_DIRECTORY /common/home/twm70/Repos/matter/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( tests_TESTS BoundaryTest.AnalyticSlipFree BoundaryTest.AnalyticSlipStick BoundaryTest.MIBF CoulombFrictionTest.PlateSlipFree CoulombFrictionTest.PlateSlipStick CoulombFrictionTest.GeneralSlipFree CoulombFrictionTest.GeneralSlipStick ElasticityTest.BulkModulus EnergyTest.Rotation CollapseTest.DruckerPragerOne CollapseTest.DruckerPragerTwo)
